# services:
#   web:
#     build: .
#     ports:
#       - '8000:8000'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - nginx # Ensure Nginx starts after FastAPI
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80' # Expose port 80 for public access
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
