name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          ssh user@your-server-ip "cd /path/to/project && git pull origin main && docker-compose up --build -d"
